Update icons to version 2.0.13
houseabsolute/dioxus-heroicons pull request #3
Opened 2023-01-02 02:30 UTC by jprider63

I updated the generator for the latest heroicon version and repository structure.

2023-01-02 21:50 UTC, autarch requested changes
Thanks for this! This looks generally good except for a few small issues.

2023-01-02 21:50 UTC, autarch commented on Cargo.toml
> +version = "2.0.13"
I don't think it makes sense to change the crate version to match the heroicons version, at least not right now. The crate has only had a few releases, so I don't want to give it a stable version number yet.

2023-01-02 21:50 UTC, autarch commented on gen/src/main.rs
> +
Please don't add whitespace changes like this.

2023-01-02 21:50 UTC, autarch commented on gen/src/main.rs
> +            Shape::{NAME} => rsx! {
Ditto here re: whitespace changes.

2023-01-02 21:50 UTC, autarch commented on gen/src/main.rs
> +        .join(",\n    ");
All of the generated code will be cleaned up with `rustfmt` anyway so there's no need to worry about whitespace in that code.

2023-01-03 00:29 UTC, jprider63 commented
Should be good now. I didn't realize you were running `rustfmt` to fix the whitespace. Let me know if you'd like me to make any other changes.

2023-01-08 16:10 UTC, autarch commented
Hi, thanks for your PR! I'm pretty finicky about my projects (see [this blog post](https://blog.urth.org/2022/07/02/what-s-the-right-way-to-merge-a-pull-request/) for details), so I rarely merge a PR as-is. I can move forward on your PR in one of two ways:

1. I check it out locally, fiddle with it as needed, merge it locally, and simply close this PR. This will preserve at least one commit with your name on it, but the PR will show up as closed in your GitHub stats.
2. If you enable me to push directly to your fork, I can do my fiddling, then force push to your fork and merge the resulting PR. Again, this will preserve at least one commit with your name on it, but you _also_ get credit for the PR merge in your GitHub stats. The only downside is that I will be force pushing directly to your fork.

Please let me know which approach you'd prefer. If I don't hear from you before I get around to working on this PR I'll go with option #1.

Thanks again for your contribution!

2023-01-09 01:02 UTC, jprider63 commented
Either works for me. You should have permission for 2 (I checked allow edits by maintainers). Let me know if you have any trouble.

2023-01-21 16:36 UTC, autarch commented
It's not letting me push to your branch for some reason. You're sure you checked the box?

2023-01-21 21:26 UTC, jprider63 commented
Yup, it's checked. No worries if it's not working.

2023-01-21 22:18 UTC, autarch commented
Very weird. I'll just go with method 1.

2023-01-21 22:19 UTC, autarch commented
Merged from the CLI.

2023-01-21 22:19 UTC, closed without merging